export function addNewSkill(skillNameNew, skillPercentNew) {
    let skillsWrapper = document.getElementById("card__skills-wrapper");
    let skillContainer = document.createElement("div");
    skillContainer.classList.add("card__skill-container");
    let skillWrapper = document.createElement("div");
    skillWrapper.style.width = "80%";
    skillWrapper.style.margin = "10px";
    let skillName = document.createElement("div");
    skillName.innerText = skillNameNew;
    let skillProgress = document.createElement("div");
    skillProgress.classList.add("card__progress");
    skillProgress.classList.add("card__progress-moved");
    let skillProgressBar = document.createElement("div");
    skillProgressBar.classList.add("card__progress-bar");
    skillProgressBar.style.width = skillPercentNew;
    skillProgressBar.animate([ { width: "5%", backgroundColor: "#98FB98"}, { width: skillPercentNew, backgroundColor: "#006400"} ], { duration: 5000 });
    let skillPercent = document.createElement("div");
    skillPercent.classList.add("card__skill-percent");
    skillPercent.innerText = skillPercentNew;
    skillPercent.style.marginLeft = skillPercentNew;
    skillPercent.animate([{ marginLeft: "5%" },  { marginLeft: skillPercentNew }], { duration: 5000 });
    let deleteButton = document.createElement("button");
    deleteButton.innerText = "Delete";
    deleteButton.addEventListener('click', () => { deleteButton.parentElement.remove(); });
    deleteButton.classList.add("card__skill-delete");
    skillWrapper.appendChild(skillName);
    skillProgress.appendChild(skillProgressBar);
    skillWrapper.appendChild(skillProgress);
    skillWrapper.appendChild(skillPercent);
    skillContainer.appendChild(skillWrapper);
    skillContainer.appendChild(deleteButton);
    skillsWrapper.appendChild(skillContainer);
}